"""Narration pipeline tests — PRESENTATION_WORKLIST §4.1-4.5.

Fixture text is the real laser curriculum from learn_history/, not invented
prose: it is the document this feature exists to narrate, and it contains every
dictionary term in its natural surroundings (markdown emphasis, percentages,
[[PMID:N]] markers) where a naive substitution breaks.

The synthesis tests stub the OpenAI call but NOT ffprobe — the stub returns
real MP3 bytes of known length generated by ffmpeg, so the timestamp map is
built from measured durations exactly as it is in production.
"""

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

import narration
import pronunciation
from pronunciation import apply_pronunciation

LEARN_HISTORY = Path(__file__).parent.parent / "learn_history"
HAVE_FFMPEG = shutil.which("ffmpeg") is not None and shutil.which("ffprobe") is not None


@pytest.fixture(autouse=True)
def isolate_cost_log(tmp_path, monkeypatch):
    """Never let a test append to the real cost_log.jsonl."""
    import endo_ai
    monkeypatch.setattr(endo_ai, "_COST_LOG_PATH", str(tmp_path / "cost_log.jsonl"))


@pytest.fixture(scope="module")
def laser_curriculum() -> str:
    """The real 'Use of lasers in root canal disinfection' curriculum answer."""
    matches = sorted(LEARN_HISTORY.glob("*lasers_in_root_canal_disinfection.json"))
    if not matches:
        pytest.skip("no laser curriculum in learn_history/")
    data = json.loads(matches[-1].read_text(encoding="utf-8"))
    return data["answer"]


# ── §4.2 Pronunciation dictionary ─────────────────────────

REQUIRED = [
    ("Er,Cr:YSGG",    "erbium chromium Y-S-G-G"),
    ("Er:YAG",        "erbium YAG"),
    ("Nd:YAG",        "neodymium YAG"),
    ("NaOCl",         "sodium hypochlorite"),
    ("EDTA",          "E-D-T-A"),
    ("PIPS",          "pips"),
    ("µm",            "microns"),
    ("MTA",           "M-T-A"),
]


@pytest.mark.parametrize("term,say", REQUIRED)
def test_required_terms_are_substituted(term, say):
    out = apply_pronunciation(f"The {term} protocol.")
    assert say in out
    assert term not in out


def test_apexification_is_respelled_and_keeps_its_capital():
    assert apply_pronunciation("apexification") != "apexification"
    # Sentence-initial capital survives; the engine must not be handed "Ay" as
    # a separate token from a lower-case respelling.
    assert apply_pronunciation("Apexification works.")[0].isupper()


def test_the_three_laser_names_survive_each_other():
    """Er,Cr:YSGG next to Er:YAG — the hybrid §4.2 warns about.

    Pins the combination, not the mechanism: the two ordering tests below cover
    that. This one fails if anyone edits the laser entries themselves.
    """
    out = apply_pronunciation("Er,Cr:YSGG and Er:YAG and Nd:YAG were compared.")
    assert out == ("erbium chromium Y-S-G-G and erbium YAG and neodymium YAG "
                   "were compared.")
    assert "Er,Cr:" not in out


def test_a_shorter_overlapping_term_cannot_pre_empt_a_longer_one():
    """The ordering rule, exercised where it is actually load-bearing.

    Guards alone are not enough. When two terms start at the SAME character —
    which is what happens the moment someone extends the map with a shorter
    prefix like 'Er' — the longer term must win, or the laser name comes out
    half-translated as 'erbium:YAG'.
    """
    extra = [{"term": "Er", "say": "erbium"}]
    assert apply_pronunciation("Er:YAG", extra_terms=extra) == "erbium YAG"
    assert apply_pronunciation("Er,Cr:YSGG", extra_terms=extra) == \
        "erbium chromium Y-S-G-G"


def test_standalone_ysgg_still_substituted():
    """The short entry must remain reachable — it is not dead data."""
    assert apply_pronunciation("The YSGG unit") == "The Y-S-G-G unit"


@pytest.mark.parametrize("word", ["EDTAC", "PIPSY", "MTAX", "XMTA", "NaOClX"])
def test_no_substitution_inside_a_longer_word(word):
    assert apply_pronunciation(f"a {word} b") == f"a {word} b"


def test_micron_symbol_attached_to_a_number_gains_a_space():
    """'500µm' must not be spoken as 'five hundredmicrons'."""
    assert apply_pronunciation("a 500µm tip") == "a 500 microns tip"
    assert apply_pronunciation("a 500 µm tip") == "a 500 microns tip"


def test_pairs_are_ordered_longest_first():
    lengths = [len(t) for t, _ in pronunciation.pronunciation_pairs()]
    assert lengths == sorted(lengths, reverse=True)


def test_extra_terms_extend_the_map_without_mutating_it():
    before = len(pronunciation.PRONUNCIATION_TERMS)
    out = apply_pronunciation("A GentleWave cycle",
                              extra_terms=[{"term": "GentleWave", "say": "gentle wave"}])
    assert out == "A gentle wave cycle"
    assert len(pronunciation.PRONUNCIATION_TERMS) == before


def test_real_curriculum_leaves_no_raw_laser_notation(laser_curriculum):
    spoken = narration.prepare_for_speech(laser_curriculum)
    for term in ("Er,Cr:YSGG", "Er:YAG", "Nd:YAG", "NaOCl", "EDTA"):
        assert term not in spoken, f"{term} reached the speech engine unconverted"
    assert "erbium chromium Y-S-G-G" in spoken
    assert "sodium hypochlorite" in spoken


def test_pronunciation_never_touches_the_displayed_text(laser_curriculum):
    """The map applies to narration only — a slide must still read 'Er:YAG'."""
    original = laser_curriculum
    narration.prepare_for_speech(laser_curriculum)
    assert laser_curriculum == original
    assert "Er:YAG" in laser_curriculum


# ── Speech cleanup ────────────────────────────────────────

def test_pmid_markers_are_never_spoken(laser_curriculum):
    assert "[[PMID:" in laser_curriculum
    spoken = narration.prepare_for_speech(laser_curriculum)
    assert "[[PMID" not in spoken and "PMID" not in spoken


def test_markdown_emphasis_is_stripped_before_the_dictionary_runs():
    assert narration.prepare_for_speech("**Er:YAG** is pulsed") == "erbium YAG is pulsed"


def test_horizontal_rules_and_headings_are_stripped():
    out = narration.strip_markdown_for_speech("## Module 1\n\n---\n\nText here.")
    assert "#" not in out and "---" not in out and "Text here." in out


# ── §4.1 Voice / model selection ──────────────────────────

def test_voice_precedence(monkeypatch):
    monkeypatch.delenv("TTS_VOICE", raising=False)
    assert narration.resolve_voice() == narration.DEFAULT_TTS_VOICE
    monkeypatch.setenv("TTS_VOICE", "shimmer")
    assert narration.resolve_voice() == "shimmer"
    assert narration.resolve_voice("nova") == "nova", "explicit request outranks env"


def test_unknown_voice_falls_back_instead_of_failing_the_export(monkeypatch):
    monkeypatch.setenv("TTS_VOICE", "sir-laurence-olivier")
    assert narration.resolve_voice() == narration.DEFAULT_TTS_VOICE


def test_model_precedence(monkeypatch):
    monkeypatch.delenv("TTS_MODEL", raising=False)
    assert narration.resolve_model() == narration.DEFAULT_TTS_MODEL
    monkeypatch.setenv("TTS_MODEL", "tts-1")
    assert narration.resolve_model() == "tts-1"
    assert narration.resolve_model("tts-1-hd") == "tts-1-hd"


# ── Sectioning and chunking ───────────────────────────────

def test_sections_split_on_module_headings(laser_curriculum):
    secs = narration.split_script_sections(laser_curriculum)
    assert len(secs) > 5
    titles = " | ".join(s["title"] for s in secs)
    assert "Module 1" in titles and "Module 4" in titles


def test_plain_prose_script_still_sections():
    """generate_audio_script() emits no markdown — paragraphs are the boundary."""
    script = "\n\n".join(f"Paragraph {i}. " + "Clinical detail. " * 30
                         for i in range(4))
    secs = narration.split_script_sections(script)
    assert len(secs) == 4
    assert all(s["title"] for s in secs)


def test_runt_paragraphs_fold_into_the_previous_section():
    script = ("Opening passage. " * 40) + "\n\nLet's move on.\n\n" + ("Second passage. " * 40)
    secs = narration.split_script_sections(script)
    assert len(secs) == 2
    assert "Let's move on." in secs[0]["text"]


def test_chunks_respect_the_api_character_cap(laser_curriculum):
    secs = narration.split_script_sections(laser_curriculum)
    for i, s in enumerate(secs):
        s["index"] = i
        s["spoken"] = narration.prepare_for_speech(s["text"])
    chunks = narration.pack_chunks(secs)
    assert chunks
    assert all(len(c["text"]) <= narration.CHUNK_CHARS for c in chunks)
    covered = {sp["section"] for c in chunks for sp in c["spans"]}
    expected = {s["index"] for s in secs if s["spoken"].strip()}
    assert covered == expected, "a section would be silently dropped from the audio"


def test_oversized_section_is_split_at_sentence_boundaries():
    huge = [{"index": 0, "spoken": "This is a sentence. " * 500}]
    chunks = narration.pack_chunks(huge, limit=1000)
    assert len(chunks) > 1
    assert all(len(c["text"]) <= 1000 for c in chunks)
    # Sentence-boundary splitting, not mid-word truncation.
    assert all(c["text"].rstrip().endswith(".") for c in chunks)


# ── §4.3 Timestamp map ────────────────────────────────────

def _silent_mp3(seconds: float, path: str) -> bytes:
    subprocess.run(
        ["ffmpeg", "-y", "-v", "error", "-f", "lavfi",
         "-i", f"anullsrc=r=24000:cl=mono", "-t", str(seconds),
         "-b:a", "32k", path],
        check=True,
    )
    return Path(path).read_bytes()


@pytest.fixture
def fake_openai_tts(monkeypatch, tmp_path):
    """Stub the API call; return REAL mp3 bytes ~1 second per 400 chars."""
    monkeypatch.setattr(narration, "openai_available", lambda: True)
    counter = {"n": 0}

    def _speak(text, voice, model):
        counter["n"] += 1
        secs = max(0.5, round(len(text) / 400.0, 2))
        return _silent_mp3(secs, str(tmp_path / f"chunk{counter['n']}.mp3"))

    monkeypatch.setattr(narration, "_speak_openai", _speak)
    return counter


@pytest.mark.skipif(not HAVE_FFMPEG, reason="ffmpeg/ffprobe not on PATH")
def test_timestamp_map_shape_and_continuity(fake_openai_tts, tmp_path,
                                            laser_curriculum):
    out = tmp_path / "lecture.mp3"
    result = narration.synthesize_lecture(
        laser_curriculum[:12000], str(out), audio_id="test-audio-1",
        media_dir=str(tmp_path), function_name="test_narration")

    tmap = result["timestamp_map"]
    assert set(tmap) >= {"version", "audio_id", "style", "backend", "voice",
                         "model", "duration_seconds", "total_chars",
                         "created_at", "slides"}
    assert tmap["audio_id"] == "test-audio-1"
    assert tmap["backend"] == "openai"
    assert tmap["duration_seconds"] > 0

    slides = tmap["slides"]
    assert len(slides) > 1
    assert [s["index"] for s in slides] == list(range(len(slides)))
    for s in slides:
        assert set(s) >= {"index", "title", "start", "end", "char_start",
                          "char_end", "preview"}
        assert s["end"] > s["start"], f"slide {s['index']} has no duration"
    for a, b in zip(slides, slides[1:]):
        assert abs(b["start"] - a["end"]) < 0.01, "gap or overlap between slides"
    assert slides[0]["start"] == 0.0
    assert abs(slides[-1]["end"] - tmap["duration_seconds"]) < 0.01, \
        "the deck would run past the end of its own audio"


@pytest.mark.skipif(not HAVE_FFMPEG, reason="ffmpeg/ffprobe not on PATH")
def test_sidecar_json_is_written_next_to_the_audio(fake_openai_tts, tmp_path):
    out = tmp_path / "lecture.mp3"
    narration.synthesize_lecture(
        "First passage. " * 60 + "\n\n" + "Second passage. " * 60,
        str(out), audio_id="sidecar-1", media_dir=str(tmp_path),
        function_name="test_narration")
    path = Path(narration.sidecar_path("sidecar-1", str(tmp_path)))
    assert path.exists()
    assert json.loads(path.read_text(encoding="utf-8"))["audio_id"] == "sidecar-1"
    assert narration.load_timestamp_map("sidecar-1", str(tmp_path))["slides"]


def test_chunk_timings_are_rescaled_to_the_probed_duration():
    """Measured chunk durations must be stretched onto the real file length.

    Concatenated MP3 frames do not always sum to what ffprobe reports for the
    joined file. Without the rescale the map drifts and slides advance early.
    """
    sections = [{"index": 0, "title": "A", "text": "a", "spoken": "a" * 100},
                {"index": 1, "title": "B", "text": "b", "spoken": "b" * 100}]
    chunks = [{"text": "x", "spans": [{"section": 0, "chars": 100}]},
              {"text": "y", "spans": [{"section": 1, "chars": 100}]}]
    tmap = narration.build_timestamp_map(
        "rescale-1", sections, chunks, [5.0, 5.0], total_duration=20.0,
        voice="onyx", model="tts-1-hd", backend="openai")
    slides = tmap["slides"]
    assert slides[0]["start"] == pytest.approx(0.0)
    assert slides[0]["end"] == pytest.approx(10.0), "10s of measured audio was stretched onto a 20s file"
    assert slides[1]["end"] == pytest.approx(20.0)


def test_load_timestamp_map_returns_empty_when_absent(tmp_path):
    assert narration.load_timestamp_map("nope", str(tmp_path)) == {}


@pytest.mark.skipif(not HAVE_FFMPEG, reason="ffmpeg/ffprobe not on PATH")
def test_explicit_sections_pin_the_map_to_slide_boundaries(fake_openai_tts, tmp_path):
    sections = [{"title": f"Slide {i}", "text": f"Passage {i}. " * 40}
                for i in range(5)]
    result = narration.synthesize_lecture(
        "unused", str(tmp_path / "a.mp3"), audio_id="pin-1",
        sections=sections, media_dir=str(tmp_path),
        function_name="test_narration")
    slides = result["timestamp_map"]["slides"]
    assert [s["title"] for s in slides] == [f"Slide {i}" for i in range(5)]


@pytest.mark.skipif(not HAVE_FFMPEG, reason="ffmpeg/ffprobe not on PATH")
def test_spoken_text_is_converted_but_slide_titles_keep_notation(fake_openai_tts,
                                                                 tmp_path):
    spoken_chunks = []
    real = narration._speak_openai

    def _capture(text, voice, model):
        spoken_chunks.append(text)
        return real(text, voice, model)

    narration._speak_openai = _capture
    try:
        result = narration.synthesize_lecture(
            "Er:YAG lasers. " * 40, str(tmp_path / "b.mp3"),
            audio_id="conv-1", media_dir=str(tmp_path),
            function_name="test_narration")
    finally:
        narration._speak_openai = real

    assert "erbium YAG" in " ".join(spoken_chunks)
    assert "Er:YAG" not in " ".join(spoken_chunks)
    # The map's preview text is display text, and keeps the notation.
    assert "Er:YAG" in result["timestamp_map"]["slides"][0]["preview"]


def test_empty_script_is_refused():
    with pytest.raises(ValueError):
        narration.synthesize_lecture("   ", "x.mp3", audio_id="e")


def test_probe_duration_returns_zero_for_a_non_audio_file(tmp_path):
    bad = tmp_path / "notaudio.mp3"
    bad.write_text("this is not an mp3")
    assert narration.probe_duration_seconds(str(bad)) == 0.0


# ── §4.5 TTS cost logging ─────────────────────────────────

def test_tts_is_priced_per_character_not_per_token(tmp_path, monkeypatch):
    import endo_ai
    log = tmp_path / "cost_log.jsonl"
    monkeypatch.setattr(endo_ai, "_COST_LOG_PATH", str(log))

    # Published rates: tts-1 $15/1M chars, tts-1-hd $30/1M chars.
    assert endo_ai.log_tts_call("t", "tts-1", 1_000_000) == pytest.approx(15.0)
    assert endo_ai.log_tts_call("t", "tts-1-hd", 1_000_000) == pytest.approx(30.0)
    assert endo_ai.log_tts_call("t", "tts-1-hd", 12_000) == pytest.approx(0.36)


def test_tts_record_is_readable_by_the_cost_aggregator(tmp_path, monkeypatch):
    """/admin/costs sums cost_usd and int()s the token fields on every row."""
    import endo_ai
    log = tmp_path / "cost_log.jsonl"
    monkeypatch.setattr(endo_ai, "_COST_LOG_PATH", str(log))
    endo_ai.log_tts_call("run_generate_audio", "tts-1-hd", 12_000,
                         mode="export", request_id="abc",
                         duration_seconds=600.0, voice="onyx")

    rec = json.loads(log.read_text(encoding="utf-8").strip())
    assert rec["kind"] == "tts"
    assert rec["characters"] == 12_000
    assert rec["input_tokens"] == 0 and rec["output_tokens"] == 0
    assert rec["model"] == "tts-1-hd" and rec["mode"] == "export"
    assert rec["voice"] == "onyx" and rec["request_id"] == "abc"
    assert rec["rate_usd_per_1m_chars"] == 30.00
    assert rec["cost_usd"] == pytest.approx(0.36)
    # Per-minute cost is the §4.5 headline number.
    assert rec["cost_usd_per_minute"] == pytest.approx(0.036)
    assert float(rec["cost_usd"]) and int(rec["input_tokens"]) == 0


def test_unknown_tts_model_bills_at_the_higher_rate(tmp_path, monkeypatch):
    """Over-reporting is the safe direction for a spend log."""
    import endo_ai
    monkeypatch.setattr(endo_ai, "_COST_LOG_PATH", str(tmp_path / "c.jsonl"))
    assert endo_ai.log_tts_call("t", "tts-9-ultra", 1_000_000) == pytest.approx(30.0)


def test_cost_logging_failure_never_breaks_an_export(tmp_path, monkeypatch):
    import endo_ai
    monkeypatch.setattr(endo_ai, "_COST_LOG_PATH",
                        str(tmp_path / "no" / "such" / "dir" / "c.jsonl"))
    assert endo_ai.log_tts_call("t", "tts-1", 1000) == pytest.approx(0.015)


@pytest.mark.skipif(not HAVE_FFMPEG, reason="ffmpeg/ffprobe not on PATH")
def test_synthesis_logs_one_cost_row(fake_openai_tts, tmp_path, monkeypatch):
    import endo_ai
    log = tmp_path / "cost_log.jsonl"
    monkeypatch.setattr(endo_ai, "_COST_LOG_PATH", str(log))
    result = narration.synthesize_lecture(
        "Passage one. " * 80, str(tmp_path / "c.mp3"), audio_id="cost-1",
        media_dir=str(tmp_path), function_name="run_generate_audio")

    rows = [json.loads(l) for l in log.read_text(encoding="utf-8").splitlines() if l]
    tts_rows = [r for r in rows if r.get("kind") == "tts"]
    assert len(tts_rows) == 1
    assert tts_rows[0]["function"] == "run_generate_audio"
    assert tts_rows[0]["request_id"] == "cost-1"
    assert tts_rows[0]["characters"] == result["characters"]
    assert result["cost_usd"] > 0
